// redux-thunk配置xx.types.js( 完成笔记 )
export const shopActionTypes = {
    AXIOS_COLLECTIONS_START: 'AXIOS_COLLECTIONS_START',
    AXIOS_COLLECTIONS_SUCCESS: 'AXIOS_COLLECTIONS_SUCCESS',
    AXIOS_COLLECTIONS_FAILURE: 'AXIOS_COLLECTIONS_FAILURE',
}