const CartActionsType = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_CART_ITEMS: 'ADD_CART_ITEMS',
    LOWER_CART_ITEMS: 'LOWER_CART_ITEMS',
    DELETE_CART_ITEM: 'DELETE_CART_ITEM',
    CLEAR_CART_ITEM: 'CLEAR_CART_ITEM',
    GET_CART_ITEM_START: 'GET_CART_ITEM_START',
    GET_CART_ITEM_SUCCESS: 'GET_CART_ITEM_SUCCESS',
    GET_CART_ITEM_FAILURE: 'GET_CART_ITEM_FAILURE',
    PUSH_CART_ITEM_START: 'PUSH_CART_ITEM_START',
    PUSH_CART_ITEM_SUCCESS: 'PUSH_CART_ITEM_SUCCESS',
    PUSH_CART_ITEM_FAILURE: 'PUSH_CART_ITEM_FAILURE',
}
export default CartActionsType;